version: "3.4"

services:
    contest:
        environment:
            real_path: "/home/fedjaz/tester/"
        image: fedjaz/contest
        ports:
            - "5000:5000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/home/fedjaz/tester/:/home/src/contest/tester/"
        network_mode: "host"
        privileged: true
